version: '3.8'

services:
  canvas-student-mcp:
    build: .
    container_name: canvas-student-mcp-server
    ports:
      - "8000:8000"
    environment:
      - CANVAS_BASE_URL=${CANVAS_BASE_URL:-https://learn.mywhitecliffe.com}
      - ENV=${ENV:-development}
      - DEBUG=${DEBUG:-true}
    volumes:
      - ./logs:/app/logs
      - ./.env:/app/.env:ro
    restart: unless-stopped
    networks:
      - canvas-mcp-network
    labels:
      - "com.docker.compose.project=canvas-student-mcp"
      - "description=Revolutionary Canvas MCP Server for Students"

  # Optional: Add Redis for session storage (future use)
  redis:
    image: redis:7-alpine
    container_name: canvas-mcp-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - canvas-mcp-network
    profiles:
      - with-redis

  # Optional: Add Nginx reverse proxy
  nginx:
    image: nginx:alpine
    container_name: canvas-mcp-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - canvas-student-mcp
    restart: unless-stopped
    networks:
      - canvas-mcp-network
    profiles:
      - with-proxy

volumes:
  redis_data:

networks:
  canvas-mcp-network:
    driver: bridge
