version: '3.8'

services:
  canvas-student-mcp:
    build: .
    container_name: canvas-student-mcp-server
    environment:
      - NODE_ENV=${NODE_ENV:-production}
      - CANVAS_API_KEY=${CANVAS_API_KEY}
      - CANVAS_BASE_URL=${CANVAS_BASE_URL:-https://canvas.instructure.com}
      - DEBUG=${DEBUG:-false}
      - ENABLE_CACHE=${ENABLE_CACHE:-true}
      - CACHE_EXPIRATION_MINUTES=${CACHE_EXPIRATION_MINUTES:-60}
      - MAX_REQUESTS_PER_MINUTE=${MAX_REQUESTS_PER_MINUTE:-100}
      - ENABLE_SMART_SEARCH=${ENABLE_SMART_SEARCH:-true}
    volumes:
      - ./logs:/app/logs
    restart: unless-stopped
    networks:
      - canvas-mcp-network
    labels:
      - "com.docker.compose.project=canvas-student-mcp"
      - "description=Canvas MCP Server v2.0 with Workflow Automation"
    # For stdio-based MCP, use docker exec to interact
    stdin_open: true
    tty: true

networks:
  canvas-mcp-network:
    driver: bridge
